/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the_jailbreak;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;

/**
 *
 * @author Romero
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();

        for (int i = 0; i < 40; i++) {
            for (int j = 0; j < 40; j++) {
                matriz[i][j] = " ";
            }

        }
        for (int i = 0; i < 40; i++) {
            matriz[i][0]="▓";
           // matriz[i][39]="▓";
            matriz[0][i]="▓";
           // matriz[39][i]="▓";
            
            
        }
        Random rnd = new Random();

        int num = rnd.nextInt(19)+1;
        matriz[num][0] = "E";
        int num2 = rnd.nextInt(39);
      //  matriz[num2][39] = "S";
        System.out.println(num);

        /* for (int i = 0; i < 5; i++) {
            System.out.println("");
            for (int j = 0; j < 5; j++) {
                System.out.print("[" + matriz[i][j] + "] ");
            }

        }*/
        int x = 0;
        int y = 0;
        
        for (int i = 0; i < 40; i++) {
            for (int j = 0; j < 40; j++) {
                if (matriz[i][j].equals("E")) {
                    x = i;
                    y = j;
                }
            }
        }
        int cont = 1;
        for (int r = 0; r < 200; r++) {
            int temp = rnd.nextInt(3);
          //  System.out.println(temp);
            
            if (cont==1) {
              matriz[x][y+1]="-";
              y=y+1;
              cont++;
            }else{
            
                if (temp == 2) {
                    int h = y + 1;
                    if (y < 39 && 0 <= y) {
                        if (matriz[x][h].equals(" ")) {
                            if (h == 39) {
                                matriz[x][h] = "S";
                            } else {
                                matriz[x][h] = "-";
                                y = y + 1;
                            }
                        }
                    }
                    if (y == 39) {
                        break;
                    }

                }

                if (temp == 0) {
                    int h = x + 1;
                    if (x < 38 && 0 <= x) {
                        if (matriz[x][h].equals(" ")) {
                            matriz[h][y] = "-";
                            x = x + 1;
                        }

                    }

                }
                //if
                if (temp == 3) {
                    int h = x - 1;
                    if (x < 38 && 0 < x) {
                        if (matriz[x][h].equals(" ")) {
                            matriz[h][y] = "-";
                            x = x - 1;
                        }
                    }

                }

            }
                int numx = 0;
                int numy = 0;

        }//fin while
        for (int i = 0; i < 1300; i++) {
            num = rnd.nextInt(39);
        
        num2 = rnd.nextInt(39);
            if (matriz[num][num2].equals(" ")) {
                matriz[num][num2]="-";
            }
            
        }
        for (int i = 0; i < 40; i++) {
            for (int j = 0; j < 40; j++) {
                if (matriz[i][j].equals(" ")) {
                    matriz[i][j]="▓";
                }
                
            }
        }
         for (int i = 0; i < 40; i++) {
            for (int j = 0; j < 40; j++) {
                if (matriz[i][j].equals("-")) {
                    matriz[i][j]="░";
                }
                
            }
        }
         
         
        
        for (int i = 0; i < 40; i++) {
            for (int j = 0; j < 40; j++) {
            }

        }//fin for
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        the_jailbreak1 = new the_jailbreak.The_jailbreak();
        the_jailbreak2 = new the_jailbreak.The_jailbreak();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1067, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private the_jailbreak.The_jailbreak the_jailbreak1;
    private the_jailbreak.The_jailbreak the_jailbreak2;
    // End of variables declaration//GEN-END:variables
String matriz[][] = new String[40][40];
}
